### ISSUE TITLE
Socket.Web.connect! throws MatchError

### ISSUE THREAD

**Issue by vysakh0** [meh/elixir-socket#63]
Using `elixir 1.3`, Used `{:socket, github: "meh/elixir-socket"}` in `mix.exs`. 

```elixir
iex(1)> socket = Socket.Web.connect! "echo.websocket.org"
** (MatchError) no match of right hand side value: %{true: [as: :binary]}
    (socket) lib/socket/tcp.ex:264: Socket.TCP.arguments/1
    (socket) lib/socket/tcp.ex:108: Socket.TCP.connect/3
    (socket) lib/socket/tcp.ex:98: Socket.TCP.connect!/2
    (socket) lib/socket/web.ex:230: Socket.Web.connect!/3


iex(1)> socket = Socket.Web.connect! "echo.websocket.org", secure: true
** (MatchError) no match of right hand side value: %{}
    (socket) lib/socket/ssl.ex:343: Socket.SSL.arguments/1
    (socket) lib/socket/ssl.ex:147: Socket.SSL.connect/3
    (socket) lib/socket/ssl.ex:131: Socket.SSL.connect!/2
    (socket) lib/socket/web.ex:230: Socket.Web.connect!/3
```

I couldn't figure out what's wrong.

**Comment by meh** [comment]
Fixed on master.
