### ISSUE TITLE
Socket.Tcp.arguments no match found for :address

### ISSUE THREAD

**Issue by bradacina** [meh/elixir-socket#74]
The example at https://hexdocs.pm/socket/Socket.html#listen/1 states:
`{ :ok, server } = Socket.listen "tcp://*:1337"`

My code:

```
defmodule Rudy.Server do
    def start() do
        { :ok, server } = Socket.listen "tcp://*:1337"
    end
end
```

Error:
```
iex(3)> x = Rudy.Server.start()
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Socket.TCP.arguments/1
    (socket) lib/socket/tcp.ex:308: anonymous fn({:address, "0.0.0.0"}) in Socket.TCP.arguments/1
    (elixir) lib/enum.ex:966: Enum.flat_map_list/2
    (elixir) lib/enum.ex:966: Enum.flat_map_list/2
    (elixir) lib/enum.ex:967: Enum.flat_map_list/2
    (socket) lib/socket/tcp.ex:282: Socket.TCP.arguments/1
    (socket) lib/socket/tcp.ex:163: Socket.TCP.listen/2
      (rudy) lib/rudy/server.ex:3: Rudy.Server.start/0
```

**Comment by meh** [comment]
Should be fixed on master, published new version, by mistake I renamed one of the options when fixing the truckload of warnings introduced by some Elixir version.

Could you test please after a `mix deps.update socket`?

**Comment by bradacina** [comment]
works. thank you .
