### ISSUE TITLE
How can I specify the raw option IP_FREEBIND when connecting to a socket?

### ISSUE THREAD

**Issue by building39** [meh/elixir-socket#83]
I tried `Socket.TCP.connect("localhost", 80, {:raw, 6, 15, :true}) and received:

** (FunctionClauseError) no function clause matching in Access.get/3

    The following arguments were given to Access.get/3:

        # 1
        {:raw, 6, 15, true}

        # 2
        :timeout

        # 3
        nil

    Attempted function clauses (showing 5 out of 5):

        def get(%{__struct__: struct} = container, key, default)
        def get(map, key, default) when is_map(map)
        def get(list, key, default) when is_list(list) and is_atom(key)
        def get(list, key, _default) when is_list(list)
        def get(nil, _key, default)

    (elixir) lib/access.ex:302: Access.get/3
    (socket) lib/socket/tcp.ex:105: Socket.TCP.connect/3

**Comment by meh** [comment]
What would the code look like with `gen_tcp`?

**Comment by building39** [comment]
{:ok, s} = :gen_tcp.connect('localhost', 80, [{:raw, 0, 15, <<1>>}, {:ip, {10, 138, 69, 63}}])
